spring:
  jpa:
    datasource:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user_db
      username: root
      password: root
      
application:
  name: service-user

security:
  charset: UTF-8
  algorithm: MD5